export const SAVE_USER_IN_STORE = 'SAVE_USER_IN_STORE'
export const LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const LOGIN_ERROR = 'AUTH_LOGIN_ERROR'
export const FETCH_USER = 'AUTH_FETCH_USER'
export const INITIAL_USER = 'AUTH_INITIAL_USER'
export const USER_CHANGED = 'AUTH_USER_CHANGED'

export const SET_ACTIVE_QUERY = 'SET_ACTIVE_QUERY'
export const LISTEN_FOR_QUERY_RESULTS = 'LISTEN_FOR_QUERY_RESULTS'
export const STOP_LISTENING_FOR_QUERY_RESULTS = 'STOP_LISTENING_FOR_QUERY_RESULTS'
export const QUERY_ADDED = 'QUERY_ADDED'

export const QUERY_RESULT_ADDED = 'QUERY_RESULT_ADDED'
export const QUERY_RESULT_CHANGED = 'QUERY_RESULT_CHANGED'

export const CREATE_USER_SESSION = 'CREATE_USER_SESSION'
export const EMPTY_STORE = 'EMPTY_STORE'

export const SUGGESTION_ADDED = 'SUGGESTION_ADDED'
export const SUGGESTION_RESULT_ADDED = 'SUGGESTION_RESULT_ADDED'
export const CLEAR_SUGGESTION_RESULTS = 'CLEAR_SUGGESTION_RESULTS'

export const CONTACT_LIST_ADDED = 'CONTACT_LIST_ADDED'
export const INITIAL_CONTACT_LISTS_FETCHED = 'INITIAL_CONTACT_LISTS_FETCHED'